spring.application.name=shppr

# Server configuration
server.port=8080

# database
spring.datasource.url=jdbc:postgresql://localhost:5432/dokan
spring.datasource.username=postgres
spring.datasource.password=4466
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true